  #configuartion status

server:
  error:
    include-message: always
    include-binding-errors: always

spring :
  jpa:
    open-in-view: false
  datasource:
    password : 123456789
    url: jdbc:postgresql://localhost:5432/agame
    username: postgres

jpa:
  hibernate:
    ddl-auto : create-drop
  properties :
    properties :
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
    show_sql : true

logging:
  root:DEBUG
